# Generated by Django 5.0 on 2024-01-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
