# Generated by Django 5.0 on 2024-01-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_vehicleowner_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleowner',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
