# Generated by Django 5.0 on 2024-01-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_vehicleowner_password'),
        ('app', '0008_comment_alter_vehicleowner_password_user'),
    ]

    operations = [
    ]
