# Generated by Django 5.0 on 2024-01-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20240106_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='vehicleowner',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='vehicleowner',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='VehicleOwner',
        ),
    ]
