# Generated by Django 5.0 on 2024-01-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_profile_name_remove_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_profile',
            name='vehicle_img',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
        migrations.AddField(
            model_name='add_profile',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
