# Generated by Django 5.0 on 2024-01-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_add_profile_vehicle_img_add_profile_vehicle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_profile',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
