# Generated by Django 5.0 on 2024-01-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_add_profile_vehicle_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profileimg', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('vehicle_name', models.CharField(blank=True, max_length=25, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=15, null=True)),
                ('vehicle_img', models.ImageField(blank=True, null=True, upload_to='profiles')),
            ],
        ),
    ]
