# Generated by Django 5.0 on 2024-01-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_vehicle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_profile',
            name='new_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
