# Generated by Django 5.0 on 2024-01-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_vehicle_owner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=25, null=True)),
                ('d_driver', models.CharField(blank=True, max_length=25, null=True)),
                ('passenger_count', models.IntegerField()),
                ('pickup_point', models.CharField(max_length=255)),
                ('dropping_point', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('uphone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
