# Generated by Django 5.0 on 2024-02-09 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_booking_d_driver_remove_booking_uphone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='app.vehicle_owner', verbose_name='driver'),
        ),
    ]
