# Generated by Django 5.0 on 2024-02-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_booking_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
