# Generated by Django 5.0 on 2024-02-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_booking_driver_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hall',
        ),
    ]
