# Generated by Django 5.0.2 on 2024-03-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_booking_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_owner',
            name='seat_count',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
