# Generated by Django 5.0.2 on 2024-03-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_vehicle_owner_seat_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_owner',
            name='end',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_owner',
            name='start',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
